[app]
video_source = "pexels"
hide_config = false
pexels_api_keys = [ "RrKQShD1Tg3tG52r9yN626mOHYT2cG7hboThfuLNKs4i43COQrs7Wf81",]
pixabay_api_keys = [ "51460692-fb579b6f12b21de9fb85cb77e",]
llm_provider = "deepseek"
pollinations_api_key = ""
pollinations_base_url = "https://pollinations.ai/api/v1"
pollinations_model_name = "openai-fast"
ollama_base_url = ""
ollama_model_name = ""
openai_api_key = ""
openai_base_url = ""
openai_model_name = "gpt-4o-mini"
moonshot_api_key = ""
moonshot_base_url = "https://api.moonshot.cn/v1"
moonshot_model_name = "moonshot-v1-8k"
oneapi_api_key = ""
oneapi_base_url = ""
oneapi_model_name = ""
g4f_model_name = "gpt-3.5-turbo"
azure_api_key = ""
azure_base_url = ""
azure_model_name = "gpt-35-turbo"
azure_api_version = "2024-02-15-preview"
gemini_api_key = "AIzaSyCMqLmegLY62sgNPVUcbvQhsRb2CzyOkA8"
gemini_model_name = "gemini-2.0-flash"
qwen_api_key = ""
qwen_model_name = "qwen-max"
deepseek_api_key = "sk-a9b460f3069c4d2fa4fd1c734bd47e7c"
deepseek_base_url = "https://api.deepseek.com"
deepseek_model_name = "deepseek-chat"
subtitle_provider = "edge"
endpoint = ""
material_directory = ""
enable_redis = false
redis_host = "localhost"
redis_port = 6379
redis_db = 0
redis_password = ""
max_concurrent_tasks = 5

[whisper]
model_size = "large-v3"
device = "CPU"
compute_type = "int8"

[proxy]

[azure]
speech_key = ""
speech_region = ""

[siliconflow]
api_key = ""

[ui]
hide_log = false
language = "en"
tts_server = "azure-tts-v1"
voice_name = "en-AU-NatashaNeural-Female"
font_name = "MicrosoftYaHeiBold.ttc"
text_fore_color = "#FFFFFF"
font_size = 60

[server]
host = "0.0.0.0"
port = 8000

