services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "streamlit", "run", "./webui/Main.py","--server.address=0.0.0.0","--server.enableCORS=True","--browser.gatherUsageStats=False" ]
    volumes:
      - ./:/MoneyPrinterTurbo
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # Se revirtió al comando original
    command: [ "python3", "main.py" ]
    volumes:
      - ./:/MoneyPrinterTurbo
    restart: always
    # Se añadió este bloque para configurar el host y puerto
    environment:
      - HOST=0.0.0.0
      - PORT=8080
