services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    command: [
      "streamlit",
      "run",
      "./webui/Main.py",
      "--server.address=0.0.0.0",
      "--server.enableCORS=True",
      "--browser.gatherUsageStats=False"
    ]
    volumes:
      - ./:/MoneyPrinterTurbo
    ports:
      - "8501:8501"  # Asegura el mapeo al puerto externo
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "python3", "main.py" ]
    volumes:
      - ./:/MoneyPrinterTurbo
    ports:
      - "8080:8080"  # Asegura el mapeo al puerto externo
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    restart: always
