x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "streamlit", "run", "./webui/Main.py","--browser.serverAddress=127.0.0.1","--server.enableCORS=True","--browser.gatherUsageStats=False" ]
    volumes:
      - *common-volumes
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "python3", "main.py" ]
    volumes:
      - *common-volumes
    restart: always
