services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "streamlit", "run", "./webui/Main.py","--server.address=0.0.0.0","--server.enableCORS=True","--browser.gatherUsageStats=False" ]
    volumes:
      - ./:/MoneyPrinterTurbo
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080" ]
    volumes:
      - ./:/MoneyPrinterTurbo
    restart: always
